# Generated by Django 5.0.1 on 2024-01-20 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_is_admin_user_is_author_user_is_games_and_more'),
        ('athletes', '0001_initial'),
        ('officials', '0001_initial'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('comcat', models.CharField(blank=True, choices=[('Sport', 'sport'), ('Game', 'game'), ('Other', 'other')], max_length=10, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'male'), ('Female', 'female')], max_length=10, null=True)),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.age')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.championship')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sport')),
            ],
        ),
        migrations.CreateModel(
            name='NGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('teams', models.ManyToManyField(to='athletes.team')),
            ],
        ),
        migrations.CreateModel(
            name='NFixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(blank=True, choices=[('Group', 'Group'), ('Knockout', 'Knockout')], max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('InPlay', 'InPlay'), ('Complete', 'Complete'), ('Postponed', 'Postponed')], default='Pending', max_length=100, null=True)),
                ('round', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('team1_score', models.IntegerField(blank=True, null=True)),
                ('team2_score', models.IntegerField(blank=True, null=True)),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='netball.ncompetition')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nteam1', to='athletes.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nteam2', to='athletes.team')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nvenue', to='venues.venue')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='netball.ngroup')),
            ],
        ),
        migrations.CreateModel(
            name='Nmatch_official',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_role', models.CharField(blank=True, choices=[('Referee', 'Referee'), ('Umpire', 'Umpire'), ('First assistant', 'First assistant '), ('Second assistant', 'Second assistant '), ('4th Official', '4th Official')], max_length=100, null=True)),
                ('fixture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='netball.nfixture')),
                ('official', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='officials.official')),
            ],
        ),
        migrations.CreateModel(
            name='NMatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('Goal', 'Goal'), ('Assist', 'Assist'), ('Foul', 'Foul'), ('Interception', 'Interception'), ('Penalty Shot', 'Penalty Shot'), ('Turnover', 'Turnover'), ('Rebound', 'Rebound'), ('Obstruction', 'Obstruction'), ('Contact', 'Contact'), ('Short Pass', 'Short Pass'), ('Long Pass', 'Long Pass'), ('Center Pass', 'Center Pass'), ('Timeout', 'Timeout')], max_length=20)),
                ('minute', models.IntegerField()),
                ('commentary', models.TextField(blank=True, null=True)),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nathlete', to='athletes.athlete')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netball.nfixture')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nteam', to='athletes.team')),
            ],
        ),
        migrations.CreateModel(
            name='NSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('participants', models.IntegerField()),
                ('groups', models.IntegerField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netball.ncompetition')),
                ('teams', models.ManyToManyField(to='athletes.team')),
            ],
        ),
        migrations.AddField(
            model_name='ngroup',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netball.nseason'),
        ),
        migrations.AddField(
            model_name='nfixture',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='netball.nseason'),
        ),
    ]
