# Generated by Django 5.0.1 on 2024-01-20 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netball', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nfixture',
            old_name='competition',
            new_name='ncompetition',
        ),
        migrations.RenameField(
            model_name='nfixture',
            old_name='group',
            new_name='ngroup',
        ),
        migrations.RenameField(
            model_name='nfixture',
            old_name='season',
            new_name='nseason',
        ),
        migrations.RenameField(
            model_name='ngroup',
            old_name='season',
            new_name='nseason',
        ),
        migrations.RenameField(
            model_name='ngroup',
            old_name='teams',
            new_name='nteams',
        ),
        migrations.RenameField(
            model_name='nmatch_official',
            old_name='fixture',
            new_name='nfixture',
        ),
        migrations.RenameField(
            model_name='nmatchevent',
            old_name='match',
            new_name='nmatch',
        ),
        migrations.RenameField(
            model_name='nmatchevent',
            old_name='team',
            new_name='nteam',
        ),
        migrations.RenameField(
            model_name='nseason',
            old_name='competition',
            new_name='ncompetition',
        ),
        migrations.RenameField(
            model_name='nseason',
            old_name='teams',
            new_name='nteams',
        ),
    ]
