# Generated by Django 5.0.1 on 2024-04-25 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_school_district_alter_school_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='EMIS',
        ),
        migrations.RemoveField(
            model_name='school',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='school',
            name='created',
        ),
        migrations.RemoveField(
            model_name='school',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='school',
            name='district',
        ),
        migrations.RemoveField(
            model_name='school',
            name='email',
        ),
        migrations.RemoveField(
            model_name='school',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='school',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='school',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='school',
            name='nin',
        ),
        migrations.RemoveField(
            model_name='school',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='school',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='school',
            name='region',
        ),
        migrations.RemoveField(
            model_name='school',
            name='status',
        ),
        migrations.RemoveField(
            model_name='school',
            name='zone',
        ),
        migrations.AlterField(
            model_name='school',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school', to=settings.AUTH_USER_MODEL),
        ),
    ]
