# Generated by Django 5.0.1 on 2024-04-25 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_is_accounts_alter_user_is_staff'),
        ('athletes', '0004_alter_team_school'),
        ('officials', '0002_remove_official_name_official_fname_official_lname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='B5Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('comcat', models.CharField(blank=True, choices=[('Sport', 'sport'), ('Game', 'game'), ('Other', 'other')], max_length=10, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'male'), ('Female', 'female')], max_length=10, null=True)),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.age')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.championship')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sport')),
            ],
        ),
        migrations.CreateModel(
            name='B5Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('b5teams', models.ManyToManyField(to='athletes.team')),
            ],
        ),
        migrations.CreateModel(
            name='B5Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(blank=True, choices=[('RegularSeason', 'Regular Season'), ('Playoffs', 'Playoffs')], max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('InPlay', 'InPlay'), ('Complete', 'Complete'), ('Postponed', 'Postponed')], default='Pending', max_length=100, null=True)),
                ('round', models.CharField(blank=True, max_length=100, null=True)),
                ('venue', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('team1_score', models.IntegerField(blank=True, null=True)),
                ('team2_score', models.IntegerField(blank=True, null=True)),
                ('team1_three_point_score', models.IntegerField(blank=True, null=True)),
                ('team2_three_point_score', models.IntegerField(blank=True, null=True)),
                ('team1_free_throw_score', models.IntegerField(blank=True, null=True)),
                ('team2_free_throw_score', models.IntegerField(blank=True, null=True)),
                ('b5competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basketball5.b5competition')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b5team1', to='athletes.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b5team2', to='athletes.team')),
                ('b5group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basketball5.b5group')),
            ],
        ),
        migrations.CreateModel(
            name='B5MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('TwoPointScore', 'Two-Point Score'), ('ThreePointScore', 'Three-Point Score'), ('FreeThrow', 'Free Throw'), ('Steal', 'Steal'), ('Assist', 'Assist'), ('Rebound', 'Rebound'), ('Foul', 'Foul'), ('Block', 'Block'), ('Turnover', 'Turnover'), ('Substitution', 'Substitution'), ('Timeout', 'Timeout')], max_length=20)),
                ('minute', models.IntegerField()),
                ('commentary', models.TextField(blank=True, null=True)),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b5athlete', to='athletes.athlete')),
                ('b5match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketball5.b5fixture')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b5team', to='athletes.team')),
            ],
        ),
        migrations.CreateModel(
            name='B5Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('participants', models.IntegerField()),
                ('groups', models.IntegerField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('b5competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketball5.b5competition')),
                ('b5teams', models.ManyToManyField(to='athletes.team')),
            ],
        ),
        migrations.AddField(
            model_name='b5group',
            name='b5season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketball5.b5season'),
        ),
        migrations.AddField(
            model_name='b5fixture',
            name='b5season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basketball5.b5season'),
        ),
        migrations.CreateModel(
            name='match_official',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_role', models.CharField(blank=True, choices=[('Referee', 'Referee'), ('Umpire', 'Umpire'), ('First assistant', 'First assistant '), ('Second assistant', 'Second assistant '), ('4th Official', '4th Official')], max_length=100, null=True)),
                ('b5fixture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basketball5.b5fixture')),
                ('b5official', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b5official', to='officials.official')),
            ],
        ),
    ]
