# Generated by Django 5.0.1 on 2024-01-21 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_is_admin_user_is_author_user_is_games_and_more'),
        ('athletes', '0001_initial'),
        ('officials', '0001_initial'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('comcat', models.CharField(blank=True, choices=[('Sport', 'sport'), ('Game', 'game'), ('Other', 'other')], max_length=10, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'male'), ('Female', 'female')], max_length=10, null=True)),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.age')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.championship')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sport')),
            ],
        ),
        migrations.CreateModel(
            name='HGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hteams', models.ManyToManyField(to='athletes.team')),
            ],
        ),
        migrations.CreateModel(
            name='HFixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(blank=True, choices=[('Group', 'Group'), ('Knockout', 'Knockout')], max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('InPlay', 'InPlay'), ('Complete', 'Complete'), ('Postponed', 'Postponed')], default='Pending', max_length=100, null=True)),
                ('round', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('team1_score', models.IntegerField(blank=True, null=True)),
                ('team2_score', models.IntegerField(blank=True, null=True)),
                ('team1_two_point_score', models.IntegerField(blank=True, null=True)),
                ('team2_two_point_score', models.IntegerField(blank=True, null=True)),
                ('hcompetition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='handball.hcompetition')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hteam1', to='athletes.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hteam2', to='athletes.team')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hvenue', to='venues.venue')),
                ('hgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='handball.hgroup')),
            ],
        ),
        migrations.CreateModel(
            name='HMatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('Goal', 'Goal'), ('PenaltyScore', 'Penalty Score'), ('FreeThrow', 'Free Throw'), ('Steal', 'Steal'), ('Assist', 'Assist'), ('Rebound', 'Rebound'), ('Foul', 'Foul'), ('Block', 'Block'), ('Turnover', 'Turnover'), ('Substitution', 'Substitution'), ('Timeout', 'Timeout')], max_length=20)),
                ('minute', models.IntegerField()),
                ('commentary', models.TextField(blank=True, null=True)),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hathlete', to='athletes.athlete')),
                ('hmatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handball.hfixture')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hteam', to='athletes.team')),
            ],
        ),
        migrations.CreateModel(
            name='HSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('participants', models.IntegerField()),
                ('groups', models.IntegerField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('hcompetition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handball.hcompetition')),
                ('hteams', models.ManyToManyField(to='athletes.team')),
            ],
        ),
        migrations.AddField(
            model_name='hgroup',
            name='hseason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handball.hseason'),
        ),
        migrations.AddField(
            model_name='hfixture',
            name='hseason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='handball.hseason'),
        ),
        migrations.CreateModel(
            name='match_official',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_role', models.CharField(blank=True, choices=[('Referee', 'Referee'), ('Umpire', 'Umpire'), ('First assistant', 'First assistant '), ('Second assistant', 'Second assistant '), ('4th Official', '4th Official')], max_length=100, null=True)),
                ('hfixture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='handball.hfixture')),
                ('hofficial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hofficial', to='officials.official')),
            ],
        ),
    ]
