# Generated by Django 5.0.1 on 2024-03-09 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('min_age', models.IntegerField(blank=True, null=True)),
                ('max_age', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lin', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='athlete_photos/')),
                ('Parent_fname', models.CharField(max_length=100)),
                ('Parent_lname', models.CharField(max_length=100)),
                ('parent_email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('parent_phone_number', models.CharField(max_length=15)),
                ('parent_nin', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('address', models.CharField(max_length=20)),
                ('relationship', models.CharField(max_length=20)),
                ('parent_gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age', to='athletes.age')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schooler', to='school.school')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport', to='accounts.sport')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom', to='athletes.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=10)),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ages', to='athletes.age')),
                ('athletes', models.ManyToManyField(to='athletes.athlete')),
                ('official', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='official', to='school.school_official')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to=settings.AUTH_USER_MODEL)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sports', to='accounts.sport')),
            ],
        ),
    ]
