# Generated by Django 5.0.1 on 2024-04-12 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_alter_athlete_lin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='name',
        ),
    ]
