# Generated by Django 5.0.1 on 2024-03-10 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('officials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='official',
            name='name',
        ),
        migrations.AddField(
            model_name='official',
            name='fname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='official',
            name='lname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='official',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='official',
            name='nin',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='official',
            name='phone_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='official',
            name='photo',
            field=models.ImageField(default='/images/profile.png', upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='official',
            name='role',
            field=models.CharField(blank=True, choices=[('Referee', 'Referee'), ('Umpire', 'Umpire')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='official',
            name='sport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='official', to='accounts.sport'),
            preserve_default=False,
        ),
    ]
